### ISSUE TITLE
MVP Suggestions

### ISSUE THREAD

**Issue by brtrick** [eric-tran2/Creatr#1]
MVPs are looking good! A couple suggestions:     
1. Be sure to include estimated time you expect to spend on each MVP.
2. Add edit capability to Photos (for, e.g., titles; needs full crUd).
3. Favorites, Likes, and Comments is a lot of functionality for a single MVP. I recommend moving Favorites and Likes to bonus.     
4. Albums would be a more substantial/impressive MVP than Search. (Search would also be easier to implement on your own later.) Consider adding Albums as an MVP and moving Search to bonus.
5. Add a seventh MVP: Production README
6. Minor point, but don't need Log In under user auth; it is covered under the "Users sign in and out" point.

**Comment by eric-tran2** [comment]
1) added estimated time for each mvp
2) added full crud
3)  shifted favorites and likes to bonus
4) added albums and shifted search to bonus
5) added readme 
6) removed redundancy

**Comment by brtrick** [comment]
Looks good!
