### ISSUE TITLE
Sample State Suggestions

### ISSUE THREAD

**Issue by brtrick** [eric-tran2/Creatr#3]
Good job with the sample state! Here are a few further suggestions:
1. For users, make username "email"
2. Probably want to include a description field under Photos.
3. Comment information is stored twice: comments includes the comment and a photo_id, and photo includes an array of associated comments. You don't need the latter. (Just use a selector on the front-end to go through the comments in state and grab the ones with the id of the photo you are interested in.) Same for tags.
4. Make the photo ids under each album an array of ids instead of an object.
5. Tags should include photoId
6. In session, only need the id of the currentUser. You can get the username from the entities.users portion of state using that id.

**Comment by eric-tran2** [comment]
1. changed username to email :+1: 
2. added description under photos 
3. removed the array of comments and tags in photos
4. changed photoIds under albums to be set into an array of ids instead of an object
5.  added photoId to tags 
6. removed username in session

**Comment by brtrick** [comment]
Looks good. Just note that your first user's email is not in correct email format (looks more like username). I'll go ahead and close this issue, but remember to update the sample state if you change your schema.
